[versions]
accompanistPermissions = "0.37.2"
activityCompose = "1.10.1"
uiautomator = "2.3.0"
walletconnect = "1.2.2"
barcodeScanning = "17.3.0"
biometric = "1.2.0-alpha05"
cameraCamera2 = "1.4.1"
coilCompose = "3.1.0"
vico = "2.0.0-alpha.21"
core = "3.5.3"
coreKtx = "1.15.0"
espressoCore = "3.6.1"
firebaseMessaging = "24.1.0"
gradle = "8.9.0"
gson = "2.12.1"
hiltAndroid = "2.55"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinGradlePlugin = "1.9.24"
kotlinSerialization = "2.0.21"
kotlinxSerializationJson = "1.8.0"
kotlinxCollectionsImmutable = "0.3.8"
kotlinxCoroutinesAndroid = "1.10.1"
lifecycleRuntimeCompose = "2.8.7"
loggingInterceptor = "4.12.0"
retrofit = "2.11.0"
review = "2.0.2"
room = "2.7.0-alpha07"
securityCrypto = "1.0.0"
compose = "1.7.6"
compose-alpha = "1.8.0-beta03"
materialIcons = "1.7.8"
material3 = "1.4.0-alpha09"
navigationCompose = "2.8.8"
uiTestJunit4 = "1.7.8"
testRunner = "1.6.2"
ksp = "2.0.21-1.0.26"
android-lib = "8.9.0"
kotlin = "2.0.21"
google-services = "4.4.2"
material3AdaptiveAndroid = "1.0.0-alpha06"
turbine = "1.2.0"
protobuf = "4.29.3"
reorderable = "2.4.3"
mockkVersion = "1.13.17"
datastore = "1.1.3"
appcompat = "1.7.0"
material = "1.12.0"
wallet-core = "4.2.12"
gemstone = "0.30.8"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
ktx-core = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinSerialization" }

# Auth and security
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

# Compose
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-alpha" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-alpha" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-runtime-android = { module = "androidx.compose.runtime:runtime-android", version.ref = "compose-alpha" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-alpha" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIcons" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

# Sqlite room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

#Google play review and notifications
play-review = { module = "com.google.android.play:review", version.ref = "review" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }

# network
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlin-serializer = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

# Json
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

#tests
junit = { module = "junit:junit", version.ref = "junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitVersion" }
androidx-junit-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTestJunit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTestJunit4" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkVersion" }
mockk-agent =  { module = "io.mockk:mockk-agent", version.ref = "mockkVersion" }

# chart
vico-m3 = { module = "com.patrykandpatrick.vico:compose-m3", version.ref = "vico" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf"}

# wallet connect
walletconnect-bom = { module = "com.reown:android-bom", version.ref = "walletconnect" }
walletconnect-core = { module = "com.reown:android-core" }
walletconnect-web3wallet = { module = "com.reown:walletkit" }

# Wallet - core
wallet-core = { module = "com.trustwallet:wallet-core", version.ref = "wallet-core" }

# Gem Stone
gemstone = { module = "com.gemwallet.gemstone:gemstone", version.ref = "gemstone" }

# qr code scanning
zxing-core = { module = "com.google.zxing:core", version.ref = "core" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCamera2" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCamera2" }

# Images
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilCompose" }

# di
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# lifecycle hold on 2.7.0 - 2.8 buggy
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeCompose" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleRuntimeCompose" }

androidx-material3-adaptive-android = { group = "androidx.compose.material3", name = "material3-adaptive-android", version.ref = "material3AdaptiveAndroid" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

datastore = { module ="androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
android-library = { id = "com.android.library", version.ref = "android-lib" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }